/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package brick.breaker;

import processing.core.PApplet;

public class App extends PApplet {
  
  /**
   *  Starts program with an instance of {@link PApplet}.
   *
   *  @param args command line arguments
   */
  public static void main(String[] args) {
    String[] processingArgs = { "App" };
    App app = new App();
    PApplet.runSketch(processingArgs, app);
  }
}
